;; keyboard binds (mostly global)
(global-set-key (kbd "C-x C-C") 'save-buffers-kill-terminal)
(global-set-key (kbd "C-x C-c") 'close-or-kill)
(global-set-key (kbd "M-w") 'copy-region-as-kill) ;;make copying not flash cursor
(global-set-key (kbd "M-(") 'wrap-region-paren)
(global-set-key (kbd "M-z") 'zap-whitespace)
(global-set-key (kbd "C-M-z") 'wrap-sexp)
(require 'buffer-move)
(global-set-key (kbd "C-x -") 'buf-move-right)
(global-set-key (kbd "M-o") 'other-window)
(global-set-key (kbd "M-c") 'calc)
(global-set-key (kbd "M-k") 'kill-current-buffer)
(global-set-key (kbd "M-K") 'kill-buffer-and-window)
(global-set-key (kbd "M-U") 'scroll-lock-mode)
(global-set-key (kbd "M-Q") 'auto-fill-mode)
(require 'dired)
(define-key dired-mode-map (kbd "C-o") 'dired-display-file)
;; (add-hook 'dired-mode-hook (lambda ()
;;                              (define-key evil-normal-state-local-map (kbd "C-o")
;;                                          'dired-display-file)))
